options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/url-shortener-repo/url-shortener', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/url-shortener-repo/url-shortener']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials gke-cluster --region us-central1 --project $PROJECT_ID
        kubectl apply -f k8s/deployment.yaml

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials gke-cluster --region us-central1 --project $PROJECT_ID
        kubectl apply -f k8s/service.yaml

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/url-shortener-repo/url-shortener'
