steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/27358/url-shortener', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/27358/url-shortener']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'gke-cluster'
      - '--region'
      - 'us-central1'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/deployment.yaml']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/service.yaml']

images:
  - 'gcr.io/27358/url-shortener'
