options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/vibrant-keyword-460710-a5/url-shortener-repo/url-shortener',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/vibrant-keyword-460710-a5/url-shortener-repo/url-shortener'
    ]

images:
  - 'us-central1-docker.pkg.dev/vibrant-keyword-460710-a5/url-shortener-repo/url-shortener'
