apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      serviceAccountName: url-shortener-ksa
      containers:
      - name: url-shortener
        image: gcr.io/27358/url-shortener
        ports:
        - containerPort: 8080
